### ISSUE TITLE
Switch interface improvement

### ISSUE THREAD

**Issue by Himura2la** [cloud4rpi/cloud4rpi#3]
I was confused by the interface of switch when I first used it. Now it seems logical, but I really had problems with it.
1. Disable the switch while sending. I expected it to act immidiately and switched it again while it was waiting for confirmation.
2. "Sending: true" and "Sending: false" is extremely confusing. At first, I thought this field shows the "sending" status. After some time, I realized the idea. I propose to write "Turning ON" and "Turning OFF". And ON/OFF in stand by mode.

**Comment by sky3d** [comment]
We added it to our backlog
